### ISSUE TITLE
react-native new-module

### ISSUE THREAD

**Issue by gabrielslach** [peggyrayzis/react-native-create-bridge#68]
### Dev setup:
- `react-native-create-bridge` version:
- `react-native` version:

### I am using create-bridge in a:

- [ ] standalone library
- [x ] existing React Native project

### What you did:
after installing this with yarn, I tried to execute the command: react-native new-module, but the command is nonexistent.

**Comment by SafdarSikander** [comment]
Same here

**Comment by jonathanmachado** [comment]
same here

**Comment by yurui-viatick** [comment]
same here

**Comment by olkunmustafa** [comment]
Same here

**Comment by nguyentrai2011** [comment]
Any solution here?

**Comment by sarthur1-0** [comment]
same here

**Comment by martan-fitsense** [comment]
same

**Comment by mela1989** [comment]
any answer about this issue?

**Comment by nomi9995** [comment]
make react-native project by react-native init projectname. then you can run this command at the root of new project

**Comment by YashYash** [comment]
Same here

**Comment by kafkas** [comment]
Same here

**Follow up:**
I had installed `react-native-create-bridge` globally. I re-installed locally and it works now

**Comment by fryercorp** [comment]
Has anyone managed to get around this?  I've tried all of the suggestions I've found whilst googling but all I get is:

$ react-native new-module
error Unrecognized command "new-module".

**Comment by kafkas** [comment]
@fryercorp Did you install `react-native-create-bridge` locally?

**Comment by fryercorp** [comment]
> 
> 
> @fryercorp Did you install `react-native-create-bridge` locally?

I ran

npm install --save react-native-create-bridge 

I can see the package in the node-modules directoy associated with my project.

I'm not sure if I'm missing any other dependencies.

**Comment by thangvo406** [comment]
same here. Any solution?

**Comment by praveens96** [comment]
same issue

**Comment by gufengpiaoyi** [comment]
same here

**Comment by novseje** [comment]
It is a missing file in ./node_modules/.bin directory.
As I understand it, it should be a modified file ./node_modules/react-native-create-bridge/build/index.js named new-module.js
With
```
(async function main() {
  init();
}()).catch();
```
instead
```
module.exports = {
  name: "new-module",
  description: "bridges React Native modules & UI components",
  func: init
};
```

**Comment by daveteu** [comment]
last commit is about 3 years ago, i guess this project is as good as abandoned.

**Comment by markrickert** [comment]
I ran into this as well. Here's how I fixed it

1. Apply @novseje's code change in `./node_modules/react-native-create-bridge/build/index.js` so that the file will run when you call it (don't bother renaming it).
3. run `node ./node_modules/react-native-create-bridge/build/index.js`
4. It works!

**Comment by JJwilkin** [comment]
^^ @markrickert  That worked for me, was able to run the command

**Comment by GhayoorUlHaq** [comment]
@markrickert It worked. Thanks!

**Comment by SurpriseMF3000** [comment]
Opposite for me.

I needed to change `./node_modules/react-native-create-bridge/build/index.js`

```
module.exports = {
  name: "new-module",
  description: "bridges React Native modules & UI components",
  func: init
};
```

to 

```
(async function main() {
  init();
}()).catch();

```

then run: `node ./node_modules/react-native-create-bridge/build/index.js` and it runs 👍 

`react-native new-module` still doesn't work
